export const PEOPLE_FETCH_REQUEST = " PEOPLE_FETCH_REQUEST";
export const PEOPLE_FETCH_SUCCESS = "PEOPLE_FETCH_SUCCESS ";
export const PEOPLE_FETCH_FAIL = "PEOPLE_FETCH_FAIL";

export const PAGE_UPDATED = " PAGE_UPDATED";
